name: "test"

# run on PR and manual trigger via github workflow ui
on: [pull_request, workflow_dispatch]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2.5.0

      - uses: ./.github/actions/build-tauri
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

